/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkhZTzMraFpwRWVoUU1oR1k1V1pQZjNKemZTTHNPYWlxZnlQd0lWWUZGOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNVhScDFYKzFWS3J5bGhDOWhVU3IvYTVYeU9uV1ZyWGpaeHA5MVF6M3hYMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNTklIeW1qWGd1RnpObWIwWmxzQ0VTTk9UV2ZjaGsya3dGZTdpQXFNWjFJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ3c2t0dkRxVllxWGdKV3Q3cDVJaGFWTm9wUSswWlpjb3BaL1NGQVpPcTNFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1OOGpYaFRhWDNabUR2QXFaNmFob1hrUnpyT2RLVzFnMHpXejlzaVg5Rjg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitVeERVcUZMZ0Zxa1Z2d1ZTT3FZL0tpSHIxWXFDbjJPckpuT1BXcGZ6R2M9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY0Y5Ri82ZWIvTHlGYlJzYms0ZjY0ZXpLNWdMWWZsOGY5SHkvQkttRnNrQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUxsdVhucExBbzBGbTFOVUhrOE51dHdQamIyemJOdFA4Y2VnaWxuelIxND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFOUzN5SHVzSGtDSnMvVjlkeFBISWZ5aU5EMVFQbUlOT3ZidWNRM1Vyb0FNTUtaR3FQM055dzljZ2hpZzVobnNnN29NWFpWaXl3QzNpQjdHVkJ2VWdnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQyLCJhZHZTZWNyZXRLZXkiOiJNTFVBTzl3YnFrdGJmaWZsREdsNkVxMkFqeHN5TE9BaVMyL3FaT0FqN3NnPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NTY4MjQxOTExMUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJDNDlFMjVGN0M2N0I0NkMyOUUzRURBNjlFQzYwRkQxNyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMyNDU0MTA5fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOnRydWV9LCJkZXZpY2VJZCI6Im43WFlkQWtQUTllb0xDRndhdUFRSUEiLCJwaG9uZUlkIjoiNDJmYjNkNGYtYWJiZS00MDQzLWEzMzktNmNhMDExYjhhN2M0IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZMVlhIQTRmS1BpWitFbE9DNlhzeld1My81Yz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTZGZMR013dzB4TUIwOG8wMzFBcDRvYWpqUzQ9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiWUFLN1FYRkQiLCJtZSI6eyJpZCI6IjI1NTY4MjQxOTExMToxNkBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJEYW5ueSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTFcyeFBvRUVMWE5qTG9HR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiYytnRm5iQmJHYWtGb2hoTTVQNDQ0Umpua3JqMDBWRlRXeDNrT24vR1owYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoibEZBdU5tK1hpU2E5dmlwQzduOFNyNStGQ0JWU1Y4SURCYlRhYnlOMU1KU2JIdC9FTU5zUDNlcjNTYlBFbDhUa0ZwUkpqRTcrV21LL1gvd1FYVkhRQnc9PSIsImRldmljZVNpZ25hdHVyZSI6InN0WTFRZS93U1lldHE0OWJCSytZOTFvQWlnTmNzODRvd1gzeXJHUFA3UGI5Nld1dVBNQ3dqRFJGbVh3alFLL2RPNzY3QzgxRit3aVNpazBtV0FHYWdRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU1NjgyNDE5MTExOjE2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlhQb0JaMndXeG1wQmFJWVRPVCtPT0VZNTVLNDlORlJVMXNkNURwL3htZEgifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzI0NTQwODMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQzBZIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "255";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '255682419111';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
