/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib0RGZ01BT3BCRDFpMEZJUHN5NFRwSXpxVWcrRExHMTBjTmVCTkIwTE5VST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRjZ0V1NYbytUQS9VWXZmTmxJa0tDQkJ5Y1dSQVk2MzBEbFhmckZpcFhIOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVTjVObHhvbTNRYWxTT04rSTZMc1cxbjZKTUY2enhhajU4emNlTUw2bkY0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZRjRjbEE1dHVyQTRJRnc4d202b215VStCNWVVa1g3VVJkcTNVdC9lZDFjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRHL3hMQVZ6bS9YQS9mM29LaWtYTmRVRUU0MFJBakY0QjFZR0tsV1dJMnM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkhrNGJYczRrN2ZFWUM0M3prdElRNGN6cUFVckdibjU4NHg5c2tISkpoUzQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ09rZloyU05aSGk0THQrYmd2cXpsODVyVGtaaG42SWxNakk2QkFUaEVYZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWXVSZDNITWlweGhJQWdTWTZlYUlWZjEwNHpLYk11WGNXSTZvSUQ2OFBXTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik44Y1JTL3V4VXo3WTJIdTJJWUJkTVZEbTY4YjgvTC8vZGdVYjJleDBna0RsQWQxSk5wc2prakpuRVkxNVhvZ0l0dW1pRVJ0LzhORlFFZEM0MzhGR2d3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjMwLCJhZHZTZWNyZXRLZXkiOiJOQ1hJZlRLNWVEN1ZURjZvUnlONTRBODFCOWpPczg4VnZXK1hOdmJnYyt3PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NTY4MjQxOTExMUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIyQTdDOUNFMkQ1N0IwMDYyMzAyQTVDOEU1N0I2QUMxQyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMyNDM1NzYzfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOnRydWV9LCJkZXZpY2VJZCI6ImNSYURUTjRPVExtS2VxU2EtVVZVLUEiLCJwaG9uZUlkIjoiMzU2MDlmOTEtMjE1Yy00NTY3LWEwNzAtYjViMjc4OTM3NjcxIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im5GSXM4NDBzNGFuU24wb2RGbk5hcUJIQzBHVT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLZUs5ekJDTThnZ1pCZGo5RjdFT0Nhbzh2eEU9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiM1RCNE1WN0YiLCJtZSI6eyJpZCI6IjI1NTY4MjQxOTExMToxNEBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJEYW5ueSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTE8yeFBvRUVQNjlpN29HR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiYytnRm5iQmJHYWtGb2hoTTVQNDQ0Umpua3JqMDBWRlRXeDNrT24vR1owYz0iLCJhY2NvdW50U2lnbmF0dXJlIjoibE10TXd5U0owU25WWS8ybEE1dDhIWllzU05qa3F5R3B1eFZ1ZHU0dUsxdCs5WllFMnBRdHBFNTdRY3Y2YVVTOUZYbjhXaWZjalUzaGdQNCtLN3hyQVE9PSIsImRldmljZVNpZ25hdHVyZSI6IkNKUkltakhRLzZpSTRwbXk1UXlubnFVSUlqS2VDR2hmQzBrVmpHbVFELzZPUTJLajFENkFmaHk0RnJjeUxERHQ4T2ZBa2dDNEZ6WUpXbmRRK051MmhnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU1NjgyNDE5MTExOjE0QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlhQb0JaMndXeG1wQmFJWVRPVCtPT0VZNTVLNDlORlJVMXNkNURwL3htZEgifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzI0MzU3MjMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQzBVIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
